### PR TITLE
remove missing ctypes.CField import dependency in Python 3.13.13

### PR DESCRIPTION
**Pull request by StatisMike**
On Windows 10 machine, with freshly installed Python 3.13.13 an error occured: `ImportError: cannot import name 'CField' from 'ctypes'`. It seems like `CField` is missing from `ctypes` in this version of Python. As Python 3.13+ is listed in dependencies, I've thought I am in the clear, but seems not.

Introduced change drops the CField dependency. Data is dumped and the output seems correct.

I know very little of Python, so without a shame: this fix was created with heavy LLM assistance.

### CODE REVIEW

**Comment by StatisMike** [comment]
master branch works with 3.14 so I'm closing this PR

**Comment by Werseter** [comment]
Addressed by bumping the minimal version requirement in README.md from 3.13+ to 3.14+ in 140e3b3aff2fffefee63744b5d3733a8c0805c1e
